#! /bin/bash

OPEN=`lsof -c vim | grep ~/.bash_eternal_history`
if [[ ! -z $OPEN ]] ; then 
#	echo "OPEN!" 
# Checks to see if .bash_eternal_history is open; if so, exit the program;
    exit
fi

cp ~/.bash_eternal_history ~/.bash_tmp

sed '/ls$/d' ~/.bash_tmp | sed '/cd$/d' | 
sed '/source \.bashrc/d' | 
#sed '/source ~/.bashrc$/d' |
sed '/sl$/d' |
sed '/\.\./d' | 
sed '/\.\.\./d' | 
sed '/nautilus \./d' | 
sed '/make/d' |
sed '/#/d' | 
sed '/git add -A/d' | 
sed '/git push/d' | 
sed '/git pull/d' |
sed '/git status/d' | 
sed '/git commit/d' | 
sed '/git init$/d' |
sed '/exit/d' |
sed '/cd -/d' |
sed '/cd$/d' |
sed '/gedit$/d' |
sed '/catkin_make$/d' |
sed '/pwd/d' |
sed '/fg/d' |
sed '/jobs$/d' |
sed '/sudo apt-get update$/d' |
sed '/ping/d' |
sed '/make/d' |
sed '/roscore/d' |
sed '/vim \.bash_eternal_history$/d' | 
sed '/ifconfig$/d' |
sed '/clean_bash_history/d' |
sed '/rqt_graph/d' |
sed '/\.\.\.\./d'  > ~/.bash_eternal_history
