#! /bin/bash
# Clock out and read the total time worked.
# Not super robust, doesn't need to be.

if [ -f ~/.out ]; then
	echo "Already clocked out"
fi
if [ -f ~/.in ]; then
	rm ~/.in
	touch ~/.out
	echo "Out: `date +%s`" >> ~/Dropbox/hours_worked.txt
	./readTime
fi
